#!/usr/bin/php
<?php
# todo : composer aotoload
require('require');
// use Core\Character;
use Core\Avatar;
use Core\Monster;
use Core\Database;

//預設角色設定
// Warrior（戰士），Mage（法師），Priest（牧師），Rogue（盜賊），Paladin（騎士） 
$pool = ['Warrior','Mage','Priest','Rogue','Paladin'];

check_user_useInterface();

# todo : 是否把戰鬥紀錄紀錄到檔案上避免跳掉後要整關重來 -> https://cloud.tencent.com/developer/article/1706987
[$name,$role] = get_userInput($pool);

$user = new Avatar($name,$role);
$monster = new Monster($name);
// dd($user);
// var_dump($user);
